### ISSUE TITLE
How to use with Gulp?

### ISSUE THREAD

**Issue by dabbyjoos** [matteobad/focus-within-polyfill#84] opened 2020-10-20 20:40 UTC
Hello -
I'm relatively new to polyfills, so I'm wondering if there's any way you can add to the readme how to use this in a Gulp file? The project I'm working on uses a Gulp file, and I would love to use this polyfill, but I'm not sure where to begin. I've searched for information, but I think maybe due to my level of familiarity, I'm having trouble figuring out how to wire this in.
Thank you!

**Comment by matteobad** [comment] 2020-11-11 10:25
Hi, it does not matter if you're using webpack, gulp, rollup... you can import the polyfill in your entrypoint or you can just link it directly inside your index.html

Closing, since it's not a bug

**Closed by matteobad** 2020-11-11 10:25 UTC
